// Isar UserProfile model
import 'package:isar/isar.dart';

// This file is part of the User model generated by Isar
part 'user.g.dart';

/// Represents a user profile in the application.
/// Annotated with @Collection to enable Isar database persistence.
/// All fields are optional to support partial updates and flexible profile creation.
@Collection()
class User {
  /// Auto-incrementing primary key identifier
  /// Uses Isar's built-in auto-increment functionality
  Id id = Isar.autoIncrement;

  /// The user's full name
  /// Indexed for faster search queries
  /// Can be null for anonymous users
  @Index()
  String? name;

  /// The user's email address
  /// Indexed for faster lookup and unique identification
  /// Can be null if email not provided
  @Index()
  String? email;

  /// A short biography/description about the user
  /// Not indexed as it's not typically used for queries
  /// Can be null if bio not provided
  String? bio;

  /// URL or path to the user's profile picture
  /// Supports:
  /// - Network URLs (https://example.com/image.jpg)
  /// - Local file paths (/data/user/0/...)
  /// - Base64 encoded image data
  /// Can be null if no image set
  String? profileImage;

  /// Timestamp of when the profile was last updated
  /// Useful for synchronization and displaying "last updated" info
  /// Automatically set to current time when saving
  DateTime? updatedAt;

  /// Note: The generated file (user.g.dart) will contain:
  /// - Isar collection implementation
  /// - Schema definition
  /// - Query builders
  /// - Serialization logic
}
